-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    Sensor1: in std_logic;
    Sensor2: in std_logic;
    Sensor3: in std_logic;
    Warnlampe: out std_logic);
end main;

architecture Behavioral of main is
begin
  Warnlampe <= ((Sensor3 AND Sensor1) OR (Sensor1 AND Sensor2) OR (Sensor2 AND Sensor3));
end Behavioral;
